source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BEKit_Example' do
  pod 'BEKit', :path => '../'
end

target 'BEKit_Tests' do
  pod 'BEKit', :path => '../'

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
